name: JMeter Load Tests

on:
  push:
    branches: 
      - jmeter-tests   # run on this branch
      - main           # optional: run on main branch too
  workflow_dispatch:   # allow manual trigger from Actions tab

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 $HOME/jmeter

      - name: Run JMeter Test Plan
        run: |
          $HOME/jmeter/bin/jmeter -n -t "Jmeter/View Results Tree.jmx" -l results.jtl -e -o report

      - name: Upload JMeter HTML Report
        uses: actions/upload-artifact@v4   # updated version
        with:
          name: jmeter-html-report
          path: report
